# Default values for kerberos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

ismaster: true
kerberos:
  realm: EXAMPLE.ORG

persistence:
  enabled: false

kdcimage:
  repository: mans0954/kerberos-kdc
  tag: latest
  pullPolicy: IfNotPresent

kadminimage:
  repository: mans0954/kerberos-kadmin
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - kdc.tier.minikube
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
