apiVersion: v1
kind: Service
metadata:
  name: {{ template "kerberos.fullname" . }}
  labels:
    app: {{ template "kerberos.name" . }}
    chart: {{ template "kerberos.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: kerberos
      protocol: TCP
      name: kerberos
  selector:
    app: {{ template "kerberos.name" . }}
    release: {{ .Release.Name }}
